Update to 3.4.13 to fix build (hi is!)
3.4.13:
Julien Danjou (3):
      Remove PREFIX, use CMAKE_INSTALL_PREFIX
      Simplify client focus code
      change codename

SÃ©bastien Luttringer (1):
      awful.titlebar use height not width

Uli Schlachter (2):
      xerror: Print numeric infos about the error
      Revert "Focus history: Don't ignore unfocusable clients"

3.4.12:
Anurag Priyam (3):
      awful.tooltip docs: replace references to undefined variable 'K' with 'myclock'
      add awful.util.table.cycle
      add awful.client.cycle

Arvydas Sidorenko (1):
      Original sky theme dwindle and spiral icons

Axel Beckert (1):
      awful.tag.inc*: properly pass tag parameter to set*

Corey Thompson (3):
      Bump duplicated commands to the most recent in command prompt history
      Initialize floating_geometry on property::border_width signal (FS#826)
      Remove "encoding=utf-8" from Vim modelines

Duflot Jean-Luc (1):
      Update french manpages

Gianluca Fiore (1):
      Add italian translation

Julien Danjou (4):
      awsetbg: xli is reported as ok
      Fix mousegrabber run documentation
      naughty: remove score system, merge presets
      change codename

Rob Hoelz (1):
      Allow usage of strings as key names for root.fake_input

SÃ©bastien Luttringer (2):
      Get mousegrabber running state
      Get keygrabber running state

Thomas Moschny (2):
      Fix build with glib2 2.31.0
      Desktop file fixes.

TsT (2):
      mistake fix: "b" local variable declaration is missing
      table.foreach is deprecated: now use for + pairs

Uli Schlachter (4):
      Beautiful: Handle invalid wallpaper_cmd better (FS#941)
      Focus history: Don't ignore unfocusable clients
      Taglist: Add {bg,fg}_occupied theme options
      awful.client.setslave: Fix for not-visible clients


3.4.11:
Anurag Priyam (1):
      naughty: add helper function, toggle() - suspend/resume notifications

Arnaud Fontaine (1):
      Update the code following release of xcb-util 0.3.8.

David Palacio (2):
      Desktop clients may not be visible on all tags.
      Ignore desktop clients on taglist widget

Ignas Anikevicius (gns_ank) (1):
      Saving gama values in pngs to prevent compilation errors

Jacques-Pascal Deplaix (1):
      awsetbg: Add the aspect option with feh

Julien Danjou (4):
      Set the conffile value before executing the code
      Use awesome.conffile in menu
      naughty: fix image data copy
      change codename

Majic (1):
      Private naughty.getIcon() -> public awful.util.geticonpath()

Massimiliano Brocchini (2):
      no duplicate entries in prompt history
      search in prompt history

Perry Hargrave (6):
      FS#917: Dont move clients with fixed positions
      Retain focus on clients moved across screens (fs#620)
      movetoscreen:Dont refocus the selected client
      Update tasklist when client screen changes
      Prevent util.cycle from infinite loop (FS#938)
      Check wallpaper_cmd entries are valid (FS#938)

Uli Schlachter (6):
      Make sure russian manpages are installed (FS#907)
      Fix restacking with zaphod mode (FS#835)
      Ungrab the server before parsing the config
      Signal config errors via a naughty popup
      Signal runtime errors via a naughty popup
      Fix the default config